name: VoxtonGen
version: 0.60
authors: [DaddyChurchill, AlbireoX]

main: net.voxton.voxtongen.CityWorld
load: startup

commands:
  cityworld:
    description: Sends you to the CityWorld
    usage: /cityworld
    