name: CityWorld
main: me.daddychurchill.CityWorld.CityWorld
version: 0.60
load: startup
author: DaddyChurchill
commands:
  cityworld:
    description: Sends you to the CityWorld
    usage: /cityworld
    